SQUARE_MODULE = 1
GAPPED_SQUARE_MODULE = 2
CIRCLE_MODULE = 3
ROUNDED_MODULE = 4
HORIZONTAL_BARS = 5
VERTICAL_BARS = 6

QRStyles = {
    SQUARE_MODULE: 1,
    GAPPED_SQUARE_MODULE: 2,
    CIRCLE_MODULE: 3,
    ROUNDED_MODULE: 4,
    HORIZONTAL_BARS: 5,
    VERTICAL_BARS: 6
}

SOLID_FILL = 1
RADIAL_GRADIANT = 2
SQUARE_GRADIANT = 3
HORIZONTAL_GRADIANT = 4
VERTICAL_GRADIANT = 5
IMAGE = 6

QRColorMasks = {
    SOLID_FILL: 1,
    RADIAL_GRADIANT: 2,
    SQUARE_GRADIANT: 3,
    HORIZONTAL_GRADIANT: 4,
    VERTICAL_GRADIANT: 5,
    IMAGE: 6
}
