# Generated by Django 5.1.5 on 2025-02-05 16:04

from django.db import migrations

def populate_full_names(apps, schema_editor):
    User = apps.get_model('accounts', 'User')
    
    for user in User.objects.all():
        email_username = user.email.split('@')[0]
        user.full_name = email_username if not user.full_name else user.full_name
        user.save()

def reverse_populate(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_remove_user_created_at_remove_user_updated_at_and_more"),
    ]

    operations = [
        migrations.RunPython(populate_full_names, reverse_populate),
    ]
