[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "core.settings"
python_files = ["test_*.py", "*_test.py"]
addopts = [
    "--strict-markers",
    "--no-migrations",
    "--cov=apps",
    "--cov-report=term-missing",
    "--cov-report=html",
]
testpaths = [
    "tests",
]